PKGFLAG   = -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS
EXTHDRS   = Alg.h Dimacs.h IntTypes.h Options.h Queue.h SolverTypes.h System.h XAlloc.h Alloc.h Heap.h Map.h ParseUtils.h Solver.h Sort.h Vec.h

include ../Makefile.in
include ../Makefile.lib
